[package]
name = "inquisitor_agent_alive"
version = "0.3.0"
authors = ["George Hosu <george@cerebralab.com>"]

[dependencies]
inquisitor_lib = {path="../../../inquisitor_lib"}
serde = "1.0.53"
serde_derive = "1.0.53"
