[package]
name = "inquisitor_agent_command_runner"
version = "0.3.0"
authors = ["George Hosu <george@cerebralab.com>"]

[dependencies]
inquisitor_lib = {path="../../../inquisitor_lib"}
serde_json = "1.0.17"
serde = "1.0.53"
serde_derive = "1.0.53"
